use master
go

DROP TABLE IF EXISTS CAFFE_MANAGER
GO

CREATE DATABASE CAFFE_MANAGER
GO

USE CAFFE_MANAGER
GO

CREATE TABLE [ROLE]
(
	[ID] INT NOT NULL PRIMARY KEY IDENTITY,
	[ROLE_NAME] VARCHAR(20) not null,
)

CREATE TABLE [USER]
(
	[USER_NAME] VARCHAR(30) NOT NULL PRIMARY KEY,
	[PASS_WORD] NVARCHAR(50) NOT NULL,
	[ROLE_ID] INT DEFAULT 2 NOT NULL,
	[FULL_NAME] NVARCHAR(50),
	[SEX] BIT,
	[ADDRESS] NVARCHAR(100),
	[YEAR_OF_BIRTH] INT,
	[PHONE] VARCHAR(15),
	[EMAIL] VARCHAR(50),
	[SALARY] INT,
	[CREATED_USER] VARCHAR(30),
	[CREATED_TIME] DATE,
	[LAST_UPDATE_USER] VARCHAR(30),
	[LAST_UPDATE_TIME] DATE,
	FOREIGN KEY([ROLE_ID]) REFERENCES [ROLE](ID)
)

CREATE TABLE CUSTOMER_TIER (
    [ID] INT PRIMARY KEY IDENTITY,
    [TIER_NAME] NVARCHAR(50) NOT NULL, -- (VD: Bronze, Silver, Gold)
    [MIN_PURCHASE] DECIMAL(10,2) NOT NULL, -- Số tiền tối thiểu để đạt cấp độ này
    [DISCOUNT_PERCENTAGE] DECIMAL(5,2) NOT NULL -- Giảm giá được hưởng
);

CREATE TABLE CUSTOMER (
    [ID] INT PRIMARY KEY IDENTITY,
    [NAME] NVARCHAR(50) NOT NULL,
    [PHONE] VARCHAR(15) NOT NULL UNIQUE,
    [EMAIL] VARCHAR(100),
    [TIER_ID] INT,
    FOREIGN KEY (TIER_ID) REFERENCES CUSTOMER_TIER(ID)
);

CREATE TABLE BEVERAGES_CATEGORY (
	[ID] INT PRIMARY KEY IDENTITY,
	[NAME] NVARCHAR(100) NOT NULL,
);

CREATE TABLE BEVERAGES (
	[ID] INT PRIMARY KEY IDENTITY,
	[NAME] NVARCHAR(100) NOT NULL,
	[PRICE] INT,
	[BEVERAGES_CATEGORY_ID] INT,
	FOREIGN KEY(BEVERAGES_CATEGORY_ID) REFERENCES BEVERAGES_CATEGORY(ID)
);