/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package GUI;

import Common.Untils;
import DAO.CustomerDAO;
import DAO.Impl.CustomerDAOImpl;
import Model.Customer;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author zero
 */
public class CustomerSearch extends javax.swing.JDialog {

    private final CustomerDAO customerDAO;
    private final DefaultTableModel modelTable;
    private ArrayList<Customer> customerList;
    private Customer customerSelected;
    
    /**
     * Creates new form InvoiceSearch
     * @param parent
     */
    public CustomerSearch(java.awt.Frame parent) {
        super(parent, "Tìm kiếm", true);
        customerDAO = new CustomerDAOImpl();
        initComponents();
        Untils.setMaxLength(txtPhone, 12);
        setLocationRelativeTo(null);
        modelTable = (DefaultTableModel) tblCustomer.getModel();
        tblCustomer.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                int selectedRow = tblCustomer.getSelectedRow();
                if (selectedRow == -1) {
                    customerSelected = null;
                }
                else {
                    if (tblCustomer.getValueAt(selectedRow, 0) instanceof Customer cus) {
                        customerSelected = cus;
                    }
                }
            }
        });
        getCustomers();
        loadCustomer();
    }
    
    public Customer getSelected(){
        return this.customerSelected;
    }
    
    private void getCustomers() {
        customerList = customerDAO.getAllCustomers();
    }
    
    /**
    * Đổ dữ liệu Warehouse cho JTable tbWarehouse.
    * 
    */
    private void loadCustomer(){
        customerSelected = null;
        modelTable.setRowCount(0);
        for (Customer customer : customerList) {
            Object[] row = new Object[4];
            row[0] = customer;
            row[1] = customer.getPhone();
            row[2] = customer.getTierName();
            row[3] = customer.getDiscountPercentage();
            modelTable.addRow(row);
        }
    }
    
    private void loadCustomer(List<Customer> customers){
        customerSelected = null;
        modelTable.setRowCount(0);
        for (Customer customer : customers) {
            Object[] row = new Object[4];
            row[0] = customer;
            row[1] = customer.getPhone();
            row[2] = customer.getTierName();
            row[3] = customer.getDiscountPercentage();
            modelTable.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCustomer = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("SĐT:");

        txtPhone.setName("Mã hóa đơn"); // NOI18N
        txtPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPhoneKeyTyped(evt);
            }
        });

        btnSearch.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/market_analysis.png"))); // NOI18N
        btnSearch.setText("Tìm kiếm");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        tblCustomer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Tên", "SĐT", "Lọa KH", "Giảm giá (%)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCustomerMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCustomer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 649, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel1)
                        .addGap(44, 44, 44)
                        .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSearch)
                        .addGap(56, 56, 56))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String phone = txtPhone.getText().trim();
        if (phone.length() > 0) {
            List<Customer> customers = new ArrayList<>();
            customers = customerList.stream().filter(cus -> cus.getPhone() == null ? false : cus.getPhone().contains(phone)).toList();
            loadCustomer(customers);
        } else {
            loadCustomer();
        }
        
    }//GEN-LAST:event_btnSearchActionPerformed

    private void txtPhoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPhoneKeyTyped
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_txtPhoneKeyTyped

    private void tblCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCustomerMouseClicked
        if (evt.getClickCount() == 2 && tblCustomer.getSelectedRow() != -1) {
            int row = tblCustomer.getSelectedRow();
             if (tblCustomer.getValueAt(row, 0) instanceof Customer cus){
                 customerSelected = cus;
                 dispose();
             }
        }
    }//GEN-LAST:event_tblCustomerMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCustomer;
    private javax.swing.JTextField txtPhone;
    // End of variables declaration//GEN-END:variables
}
