/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import Common.Constants;
import Common.Untils;
import Common.UserSession;
import Enums.Roles;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/**
 *
 * @author zero
 */
public class Menu extends javax.swing.JPanel {

    private final JPanel cardPanel;
    /**
     * Creates new form Menu
     * @param cardPanel
     */
    public Menu(JPanel cardPanel) {
        this.cardPanel = cardPanel;
        initComponents();
        
        SwingUtilities.invokeLater(() -> {
            if (UserSession.getInstance().getRole() == Roles.MANAGER) {
                Untils.setImageButton(btnBeveragesManage, "themmon.jpg");
                Untils.setImageButton(btnRevenue, "quanlydoanhthu.jpg");
                Untils.setImageButton(btnStaffManagement, "quanlynhanvien.jpg");
                Untils.setImageButton(btnCustomerManagement, "quanlyloaikhachhang.png");
                Untils.setImageButton(btnInvoiceManagement, "quanlyhoadon.png");
                Untils.setImageButton(btnWarehouseManagement, "nhapKho.jpeg");
            }
            Untils.setImageButton(btnBilling, "thanhToan.jpg");
            Untils.setImageButton(btnInputWarehouse, "nhapKho.jpeg");
        });
        if (UserSession.getInstance().getRole() == Roles.STAFF) {
            btnBeveragesManage.setVisible(false);
            btnRevenue.setVisible(false);
            btnStaffManagement.setVisible(false);
            btnCustomerManagement.setVisible(false);
            btnInvoiceManagement.setVisible(false);
            btnWarehouseManagement.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        btnStaffManagement = new javax.swing.JButton();
        btnCustomerManagement = new javax.swing.JButton();
        btnBilling = new javax.swing.JButton();
        btnRevenue = new javax.swing.JButton();
        btnBeveragesManage = new javax.swing.JButton();
        btnInvoiceManagement = new javax.swing.JButton();
        btnWarehouseManagement = new javax.swing.JButton();
        btnInputWarehouse = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(500, 400));
        setPreferredSize(new java.awt.Dimension(500, 400));
        setLayout(new java.awt.GridBagLayout());

        btnStaffManagement.setToolTipText("Quản lý nhân viên");
        btnStaffManagement.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnStaffManagement.setMinimumSize(new java.awt.Dimension(200, 200));
        btnStaffManagement.setPreferredSize(new java.awt.Dimension(200, 200));
        btnStaffManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStaffManagementActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(btnStaffManagement, gridBagConstraints);

        btnCustomerManagement.setToolTipText("Quản lý chương trình giảm giá khách hàng");
        btnCustomerManagement.setMinimumSize(new java.awt.Dimension(200, 200));
        btnCustomerManagement.setPreferredSize(new java.awt.Dimension(200, 200));
        btnCustomerManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomerManagementActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(btnCustomerManagement, gridBagConstraints);

        btnBilling.setToolTipText("Thanh toán");
        btnBilling.setMinimumSize(new java.awt.Dimension(200, 200));
        btnBilling.setPreferredSize(new java.awt.Dimension(200, 200));
        btnBilling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBillingActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(btnBilling, gridBagConstraints);

        btnRevenue.setToolTipText("Quản lý doanh thu");
        btnRevenue.setMinimumSize(new java.awt.Dimension(200, 200));
        btnRevenue.setPreferredSize(new java.awt.Dimension(200, 200));
        btnRevenue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRevenueActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(btnRevenue, gridBagConstraints);

        btnBeveragesManage.setToolTipText("Thêm món");
        btnBeveragesManage.setMinimumSize(new java.awt.Dimension(200, 200));
        btnBeveragesManage.setPreferredSize(new java.awt.Dimension(200, 200));
        btnBeveragesManage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBeveragesManageActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(btnBeveragesManage, gridBagConstraints);

        btnInvoiceManagement.setToolTipText("Quản lý hoá đơn");
        btnInvoiceManagement.setMinimumSize(new java.awt.Dimension(200, 200));
        btnInvoiceManagement.setPreferredSize(new java.awt.Dimension(200, 200));
        btnInvoiceManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInvoiceManagementActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(btnInvoiceManagement, gridBagConstraints);

        btnWarehouseManagement.setToolTipText("Lịch sử bán hàng");
        btnWarehouseManagement.setMinimumSize(new java.awt.Dimension(200, 200));
        btnWarehouseManagement.setPreferredSize(new java.awt.Dimension(200, 200));
        btnWarehouseManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWarehouseManagementActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(btnWarehouseManagement, gridBagConstraints);

        btnInputWarehouse.setToolTipText("Nhập kho");
        btnInputWarehouse.setMinimumSize(new java.awt.Dimension(200, 200));
        btnInputWarehouse.setPreferredSize(new java.awt.Dimension(200, 200));
        btnInputWarehouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInputWarehouseActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(btnInputWarehouse, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBeveragesManageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBeveragesManageActionPerformed
        MainFrame.showScreen(cardPanel, Constants.BEVERAGES_MANAGE);
    }//GEN-LAST:event_btnBeveragesManageActionPerformed

    private void btnStaffManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStaffManagementActionPerformed
        MainFrame.showScreen(cardPanel, Constants.STAFF_MANAGE);
    }//GEN-LAST:event_btnStaffManagementActionPerformed

    private void btnCustomerManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerManagementActionPerformed
        MainFrame.showScreen(cardPanel, Constants.CUSTOMER_MANAGE);
    }//GEN-LAST:event_btnCustomerManagementActionPerformed

    private void btnBillingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBillingActionPerformed
        MainFrame.showScreen(cardPanel, Constants.BILLING);
    }//GEN-LAST:event_btnBillingActionPerformed

    private void btnRevenueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRevenueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRevenueActionPerformed

    private void btnInvoiceManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInvoiceManagementActionPerformed
        MainFrame.showScreen(cardPanel, Constants.INVOICE_MANAGE);
    }//GEN-LAST:event_btnInvoiceManagementActionPerformed

    private void btnWarehouseManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWarehouseManagementActionPerformed
        MainFrame.showScreen(cardPanel, Constants.WAREHOUSE_MANAGE);
    }//GEN-LAST:event_btnWarehouseManagementActionPerformed

    private void btnInputWarehouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInputWarehouseActionPerformed
         MainFrame.showScreen(cardPanel, Constants.INPUT_WAREHOUSE);
    }//GEN-LAST:event_btnInputWarehouseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBeveragesManage;
    private javax.swing.JButton btnBilling;
    private javax.swing.JButton btnCustomerManagement;
    private javax.swing.JButton btnInputWarehouse;
    private javax.swing.JButton btnInvoiceManagement;
    private javax.swing.JButton btnRevenue;
    private javax.swing.JButton btnStaffManagement;
    private javax.swing.JButton btnWarehouseManagement;
    // End of variables declaration//GEN-END:variables
}
